using BegaProductFinder.Core.Models;

namespace BegaProductFinder.Core.Interfaces;

/// <summary>
/// Hybrid product search combining vector similarity (pgvector) with structured SQL filtering.
/// Used by the <c>search_products</c>, <c>filter_by_specs</c>, and <c>get_product_detail</c> Claude tools.
/// </summary>
public interface IProductSearchService
{
    /// <summary>
    /// Performs a hybrid search: embeds the query, runs pgvector ANN search, then re-ranks
    /// results with SQL-side filters from <paramref name="filters"/>.
    /// Furniture products (identified by GroupSlug) are excluded from results.
    /// </summary>
    /// <param name="query">Natural language search query e.g. "exterior in-grade luminaire 24V dark sky".</param>
    /// <param name="filters">Optional structured filters applied after vector retrieval.</param>
    /// <returns>Ranked list of matching luminaire products.</returns>
    Task<List<ProductSearchResult>> SearchByNaturalLanguageAsync(
        string query,
        ProductSearchFilters? filters = null,
        CancellationToken ct = default);

    /// <summary>
    /// Parallel multi-query variant: embeds <paramref name="query"/> and all
    /// <paramref name="expandedQueries"/> concurrently, runs a vector search for each,
    /// merges the candidate pools by keeping the highest score per product, then applies
    /// SQL filters and diversity ranking. Improves recall over single-query search.
    /// </summary>
    /// <param name="query">Primary natural language query.</param>
    /// <param name="expandedQueries">Synonym / related-concept queries generated by Claude's search expansion layer.</param>
    /// <param name="filters">Optional structured filters applied after vector retrieval.</param>
    Task<List<ProductSearchResult>> SearchByNaturalLanguageAsync(
        string query,
        IReadOnlyList<string> expandedQueries,
        ProductSearchFilters? filters = null,
        CancellationToken ct = default);

    /// <summary>
    /// Applies precise numerical filters to product spec columns without vector search.
    /// Used for queries with exact numerical requirements e.g. "lumens >= 500".
    /// </summary>
    /// <param name="filters">One or more <see cref="SpecFilter"/> conditions — all must match (AND logic).</param>
    Task<List<ProductSearchResult>> FilterBySpecsAsync(
        List<SpecFilter> filters,
        CancellationToken ct = default);

    /// <summary>
    /// Retrieves the full specification record for a single product by catalog number.
    /// Returns null if the catalog number does not exist in the database.
    /// </summary>
    /// <param name="catalogNumber">BEGA catalog number e.g. "77127".</param>
    Task<ProductDetail?> GetProductDetailAsync(
        string catalogNumber,
        CancellationToken ct = default);

    /// <summary>
    /// Finds alternative products to the one identified by <paramref name="catalogNumber"/> —
    /// other products in the same family (preferring the same sub-family), ranked by closeness
    /// of lumen output to the source product. Pure SQL lookup, no embeddings or Claude calls.
    /// </summary>
    /// <param name="catalogNumber">BEGA catalog number of the source product.</param>
    /// <param name="topK">Maximum number of alternatives to return.</param>
    /// <param name="excludeCatalogNumbers">Catalog numbers to skip — typically products already shown earlier in the conversation, so repeated lookups surface new options.</param>
    Task<List<ProductSearchResult>> GetAlternativesAsync(
        string catalogNumber,
        int topK = 3,
        IReadOnlyList<string>? excludeCatalogNumbers = null,
        CancellationToken ct = default);
}
