// <auto-generated />
using System;
using BegaProductFinder.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BegaProductFinder.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611115104_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BegaProductFinder.Core.Models.ChatSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sessionid");

                    b.Property<string>("ContextJson")
                        .HasColumnType("text")
                        .HasColumnName("contextjson");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastactivityat");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]")
                        .HasColumnName("messagesjson");

                    b.HasKey("SessionId")
                        .HasName("pk_chatsessions");

                    b.ToTable("chatsessions", (string)null);
                });

            modelBuilder.Entity("BegaProductFinder.Core.Models.ContactInquiry", b =>
                {
                    b.Property<int>("InquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("inquiryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InquiryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sessionid");

                    b.HasKey("InquiryId")
                        .HasName("pk_contactinquiries");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_contactinquiries_email");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_contactinquiries_sessionid");

                    b.ToTable("contactinquiries", (string)null);
                });

            modelBuilder.Entity("BegaProductFinder.Core.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("AIEnrichmentJson")
                        .HasColumnType("text")
                        .HasColumnName("aienrichmentjson");

                    b.Property<string>("Application")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("application");

                    b.Property<decimal?>("BeamAngleDeg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("beamangledeg");

                    b.Property<string>("BegaId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("begaid");

                    b.Property<string>("CatalogNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("catalognumber");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoryname");

                    b.Property<string>("ColorTemperatureJson")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("colortemperaturejson");

                    b.Property<string>("ControlProtocol")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("controlprotocol");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DimensionA")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dimensiona");

                    b.Property<string>("DimensionAFraction")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dimensionafraction");

                    b.Property<string>("DimensionB")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dimensionb");

                    b.Property<string>("DimensionBFraction")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dimensionbfraction");

                    b.Property<string>("DimensionC")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dimensionc");

                    b.Property<string>("DimensionCFraction")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dimensioncfraction");

                    b.Property<string>("DimensionD")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dimensiond");

                    b.Property<string>("DimensionDFraction")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dimensiondfraction");

                    b.Property<string>("DimensionE")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dimensione");

                    b.Property<string>("DimensionEFraction")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dimensionefraction");

                    b.Property<string>("Distribution")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("distribution");

                    b.Property<decimal?>("DnpPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("dnpprice");

                    b.Property<string>("DynamicLight")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dynamiclight");

                    b.Property<string>("ExtraInfo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("extrainfo");

                    b.Property<string>("FamilyExtraInfo")
                        .HasColumnType("text")
                        .HasColumnName("familyextrainfo");

                    b.Property<string>("FamilyListPageImage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("familylistpageimage");

                    b.Property<string>("FamilyListPageImageOrientation")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("familylistpageimageorientation");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("familyname");

                    b.Property<string>("FamilySlug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("familyslug");

                    b.Property<string>("FamilyTechImage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("familytechimage");

                    b.Property<string>("Finish")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("finish");

                    b.Property<string>("GroupSlug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("groupslug");

                    b.Property<string>("GroupsName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("groupsname");

                    b.Property<bool>("IsAdaCompliant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isadacompliant");

                    b.Property<bool>("IsExpressDelivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isexpressdelivery");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastupdated");

                    b.Property<string>("LeadTime")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("leadtime");

                    b.Property<string>("LedWattage")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ledwattage");

                    b.Property<decimal?>("LumenOutputLm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("lumenoutputlm");

                    b.Property<string>("LuminaireType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("luminairetype");

                    b.Property<decimal?>("MsrpPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("msrpprice");

                    b.Property<string>("ProductOptionsJson")
                        .HasColumnType("text")
                        .HasColumnName("productoptionsjson");

                    b.Property<string>("ProductTechnicalSpec")
                        .HasColumnType("text")
                        .HasColumnName("producttechnicalspec");

                    b.Property<string>("RatingB")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ratingb");

                    b.Property<string>("RatingG")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ratingg");

                    b.Property<string>("RatingU")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ratingu");

                    b.Property<string>("ReplacementCatalogNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("replacementcatalognumber");

                    b.Property<string>("SocialEnviornmentalHealth")
                        .HasColumnType("text")
                        .HasColumnName("socialenviornmentalhealth");

                    b.Property<string>("SpecDocumentUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("specdocumenturl");

                    b.Property<string>("SubFamilyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subfamilyname");

                    b.Property<decimal?>("SystemWattageW")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("systemwattagew");

                    b.Property<string>("TechnicalDocumentUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("technicaldocumenturl");

                    b.Property<string>("Voltage")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("voltage");

                    b.Property<decimal?>("WattageW")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("wattagew");

                    b.HasKey("ProductId")
                        .HasName("pk_products");

                    b.HasIndex("BegaId")
                        .IsUnique()
                        .HasDatabaseName("ix_products_begaid");

                    b.HasIndex("CatalogNumber")
                        .HasDatabaseName("ix_products_catalognumber");

                    b.HasIndex("CategoryName")
                        .HasDatabaseName("ix_products_categoryname");

                    b.HasIndex("FamilyName")
                        .HasDatabaseName("ix_products_familyname");

                    b.HasIndex("GroupSlug")
                        .HasDatabaseName("ix_products_groupslug");

                    b.HasIndex("LuminaireType")
                        .HasDatabaseName("ix_products_luminairetype");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("BegaProductFinder.Core.Models.ProductAccessory", b =>
                {
                    b.Property<int>("AccessoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("accessoryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccessoryId"));

                    b.Property<string>("AccessoryName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("accessoryname");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sortorder");

                    b.HasKey("AccessoryId")
                        .HasName("pk_productaccessories");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_productaccessories_productid");

                    b.ToTable("productaccessories", (string)null);
                });

            modelBuilder.Entity("BegaProductFinder.Core.Models.ProductChunk", b =>
                {
                    b.Property<int>("ChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("chunkid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChunkId"));

                    b.Property<string>("CatalogNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("catalognumber");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunkindex");

                    b.Property<string>("ChunkSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chunksource");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chunktext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsEmbedded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isembedded");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pagenumber");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<string>("VectorId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("vectorid");

                    b.HasKey("ChunkId")
                        .HasName("pk_productchunks");

                    b.HasIndex("CatalogNumber")
                        .HasDatabaseName("ix_productchunks_catalognumber");

                    b.HasIndex("IsEmbedded")
                        .HasDatabaseName("ix_productchunks_isembedded");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_productchunks_productid");

                    b.ToTable("productchunks", (string)null);
                });

            modelBuilder.Entity("BegaProductFinder.Core.Models.ProductProject", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("projectid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ListingImage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("listingimage");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("productid");

                    b.Property<string>("Slug")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sortorder");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tags");

                    b.HasKey("ProjectId")
                        .HasName("pk_productprojects");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_productprojects_productid");

                    b.ToTable("productprojects", (string)null);
                });

            modelBuilder.Entity("BegaProductFinder.Core.Models.ProductAccessory", b =>
                {
                    b.HasOne("BegaProductFinder.Core.Models.Product", "Product")
                        .WithMany("Accessories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productaccessories_products_productid");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BegaProductFinder.Core.Models.ProductChunk", b =>
                {
                    b.HasOne("BegaProductFinder.Core.Models.Product", "Product")
                        .WithMany("Chunks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productchunks_products_productid");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BegaProductFinder.Core.Models.ProductProject", b =>
                {
                    b.HasOne("BegaProductFinder.Core.Models.Product", "Product")
                        .WithMany("Projects")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productprojects_products_productid");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BegaProductFinder.Core.Models.Product", b =>
                {
                    b.Navigation("Accessories");

                    b.Navigation("Chunks");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
